const styles = {
  container: {
    flex: 1,
  },
  card: {
    margin: 10,
    borderRadius: 10,
    padding: 10,
    backgroundColor: "#8C8C8C",
    position: "relative",
    elevation: 3,
  },
  mailIconContainer: {
    position: "absolute",
    top: 0,
    right: 0,
    flexDirection: "column",
    alignItems: "center",
    margin: 9,
    padding: 15,
  },
  email: {
    color: "white",
    fontSize: 12,
    fontWeight: "bold",
    alignItems: "flex-end",
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  photoContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: "hidden",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#000000",
  },
  photo: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  mainUserInfo: {
    flex: 1,
    flexDirection: "row",
  },
  detailsUsername: {
    color: "orange",
    fontSize: 15,
    fontWeight: "bold",
  },
  buttonsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 8,
    gap: 15,
  },
  updateButton: {
    backgroundColor: "orange",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    flex: 1,
    marginRight: 8,
  },
  buttonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  postsTitle: {
    color: "white",
    fontSize: 12,
    margin: 5,
    padding: 1,
  },
  deleteButton: {
    backgroundColor: "#dc3545",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    flex: 1,
    marginLeft: 8,
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    margin: 0,
    backgroundColor: "#8C8C8C",
    borderBottomWidth: 1,
    borderBottomColor: "orange",
    borderRadius: 10,
    borderTopStartRadius: 0,
    borderTopEndRadius: 0,
    elevation: 3,
  },
  avatarContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    overflow: "hidden",
    marginRight: 15,
    borderWidth: 1,
    borderColor: "#ffffff",
  },
  nameMail: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  nameCompany: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  avatar: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  userInfo: {
    flex: 1,
    alignItems: "center",
  },
  username: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 5,
    color: "white",
  },
  city: {
    fontSize: 14,
    color: "white",
  },
  mainCard: {
    backgroundColor: "#8C8C8C",
    borderWidth: 1,
    borderColor: "#898989",
    margin: 15,
    padding: 15,
    borderRadius: 10,
    elevation: 3,
  },
  name: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 18,
    color: "orange",
  },
  company: {
    fontSize: 16,
    color: "white",
    margin: 5,
    padding: 5,
  },
  phone: {
    fontSize: 16,
    color: "white",
    marginBottom: 8,
    padding: 5,
    margin: 5,
  },
  website: {
    fontSize: 16,
    color: "white",
    fontWeight: "bold",
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: "orange",
    borderRadius: 14,
    padding: 10,
    margin: 5,
  },
  postContainer: {
    margin: 8,
    padding: 2,
    borderRadius: 1,
  },
  mailContainer: {
    flex: 1,
    alignItems: "center",
  },

  mainEmail: {
    fontSize: 14,
    color: "white",
  },
  postHeader: {
    fontSize: 20,
    fontWeight: "bold",
    margin: 0,
    alignSelf: "center",
    padding: 0,
    color: "white",
  },
  postTitle: {
    margin: 5,
    padding: 5,
  },
  modalOverlay: {
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    alignSelf: "auto",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8C8C8C",
    width: "100%",
    height: "100%",
    padding: 20,
    borderWidth: 3,
    borderColor: "white",
    borderRadius: 15,
    elevation: 20,
  },
  text: {
    margin: 5,
    fontWeight: "bold",
    color: "orange",
  },
  headerText: {
    fontSize: 18,
    alignSelf: "center",
  },
  errorText: {
    color: "red",
    marginVertical: 5,
    fontSize: 14,
  },
  button: {
    borderRadius: 24,
    paddingVertical: 8,
    paddingHorizontal: 12,
    justifyContent: "center",
    alignItems: "center",
    minWidth: 100,
  },
  closeButton: {
    backgroundColor: "#dc3545",
    marginRight: 10,
  },
  saveButton: {
    backgroundColor: "#007bff",
  },
  input: {
    margin: 5,
    fontSize: 13,
    borderWidth: 1,
    borderColor: "#C9C9C9",
    color: "white",
    borderRadius: 14,
    padding: 8,
    width: 250,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "#C9C9C9",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  createButton: {
    backgroundColor: "#00bfff",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    flex: 1,
    marginRight: 8,
  },
  cancelButton: {
    backgroundColor: "#dc3545",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    flex: 1,
    marginLeft: 8,
  },
  backgroundImage: {
    flex: 1,
    resizeMode: "repeat",
    backgroundColor: "url(../assets/icon.png)",
    padding: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E9E2E0",
  },
  newUserButton: {
    backgroundColor: "#00bfff",
    padding: 10,
    borderRadius: 5,
    margin: 10,
  },
  newUserButtonText: {
    color: "#fff",
    fontSize: 16,
  },
};

export default styles;
